### ISSUE TITLE
Update SDK to be compliant with spec v0.2.0

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/node-sdk#138]
Update the SDK to be compliant with the v0.2.0 spec.

## Flag Evaluation API
- [x]  [#116](https://github.com/open-feature/spec/pull/116) - Have different methods for float and int

## Providers
- [x] #140

## Evaluation Context
- [x] #141
- [x]  [#120](https://github.com/open-feature/spec/pull/120) - Add the ability to fetch all custom fields
- [x]  [#121](https://github.com/open-feature/spec/pull/121) - Ensure evaluation context keys are unique

## Hooks
- [x] #142

**Full Changelog**: https://github.com/open-feature/spec/compare/v0.1.0...v0.2.0

**Comment by toddbaert** [comment]
120 - I believe is "free" in JS... we can use `Object.keys` I think.
121 - I think this is more or less "for free" too, and we already freeze the object after the before hooks.

119 - seems like it will be done with the testing of https://github.com/open-feature/node-sdk/issues/140
